import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        String temp="";
        String[] orderID=new String[inputs.size()];
        int[] orderNum=new int[inputs.size()];
        for(int i=0;i<inputs.size();i++){
            orderID[i]=inputs.get(i).split(" x ")[0];
            orderNum[i]=Integer.parseInt(inputs.get(i).split(" x ")[1]);
        }
        int totalPrice=0,cutPrice=0,halfPrice=0,halfPro=0,isPromotion=0;
        String promotion="(";
        temp+="============= Order details =============\n";
        List<Item>items=itemRepository.findAll();
        List<SalesPromotion>all=salesPromotionRepository.findAll();
        List<String>promos=new ArrayList<>();
        for(int i=0;i<all.size();i++){
            if(all.get(i).getType().equals("50%_DISCOUNT_ON_SPECIFIED_ITEMS")){
                promos=all.get(i).getRelatedItems();
            }
        }
        for(int i=0;i<orderID.length;i++){
            for (int j=0;j<items.size();j++){
                if(orderID[i].equals(items.get(j).getId())){
                    temp+=items.get(j).getName() + " x " + orderNum[i] + " = " + (int)(items.get(j).getPrice() * orderNum[i] )+ " yuan\n";
                    totalPrice+=items.get(j).getPrice() * orderNum[i];
                    String itemName=items.get(j).getId();
                    if(judge(promos,itemName)==1){
                        cutPrice+=items.get(j).getPrice()*orderNum[i]/2;
                        if(isPromotion==0){
                            promotion+=items.get(j).getName();
                            isPromotion=1;
                        }else {
                            promotion+="，"+items.get(j).getName();
                        }
                    }else {
                        cutPrice+=items.get(j).getPrice()*orderNum[i];
                    }
                    break;
                    }
                }
            }
        temp+="-----------------------------------\n";
        if(totalPrice>=30){
            halfPro=1;
            halfPrice=totalPrice-6;
        }else {
            halfPrice=totalPrice;
        }
        if(!(halfPro==0&&isPromotion==0)){
            temp+="Promotion used:\n";
            if(halfPrice<=cutPrice){
                temp+="满30减6 yuan，saving 6 yuan\n";
                temp+="-----------------------------------\n";
                temp+="Total：" + halfPrice + " yuan\n";
            }else {
                temp+="Half price for certain dishes " + promotion + ")，" + "saving " + (int)(totalPrice - cutPrice) + " yuan\n";
                temp+="-----------------------------------\n";
                temp+="Total：" + cutPrice + " yuan\n";
            }
        }else {
            temp+="Total："+totalPrice+" yuan\n";
        }
        temp+="===================================";
        return temp;
    }

    int judge(List<String>promos,String itemName){
        for(int k=0;k<promos.size();k++){
            if(itemName.equals(promos.get(k))){
                return 1;
            }
        }
        return 0;
    }
}
